/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/sun.glb 
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-9ef1c68fbb944147bcfcc891d3912645
Title: Sun
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'


export function Model(props) {
  const group = React.useRef() // This is the ref attached to your model group
  const { nodes, materials, animations } = useGLTF('/sun.glb')
  const { actions } = useAnimations(animations, group)
  
  // Corrected animation loop
  useFrame((state, delta) => {
    if (group.current) {
      // Rotate the sun on its Y axis
      group.current.rotation.y += delta * 0.2; // Adjust 0.5 to make it faster or slower
    }
  })

  return (
    // The 'group' ref is correctly assigned here
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="3a2aaa22fb3d4b329318a980ad1bf6d1fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="UnstableStarCore" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="UnstableStarCore_1_0" geometry={nodes.UnstableStarCore_1_0.geometry} material={materials.material}>
                    <meshStandardMaterial
                      color="#ffc300"
                      emissive="#ffc300"      // The color of the glow
                      emissiveIntensity={0.5}   // How strong the glow is
                    />
                  </mesh>
                </group>
                <group name="UnstableStarref" rotation={[-Math.PI / 2, 0, 0]} scale={1.01}>
                  <mesh name="UnstableStarref_2_0" geometry={nodes.UnstableStarref_2_0.geometry} material={materials.material_1} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sun.glb')